[tool.poetry]
name = "fairseq"
version = "0.1.0"
description = ""
authors = ["migo migoxv@gmail.com"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"  # specify the version range for Python
numpy = ">=1.21.3"
torch = ">=1.10"
cython = "*"
hydra = "*"
scipy = "*"
# matplotlib = "*"
# add other dependencies here

[tool.poetry.dev-dependencies]
setuptools = ">=18.0"
wheel = "*"
black = "*"
isort = "*"

[tool.poetry.scripts]
# Add any CLI tools here if required

[tool.black]
extend-exclude = '''
(
^/examples/| 
^/fairseq/model_parallel/megatron| 
^/build/
)
'''

[tool.isort]
profile = "black"
known_third_party = "_cffi_backend,agg_results,aml,bitarray,boto3,botocore,dump_hubert_feature,dynamicconv_cuda,editdistance,faiss,fasttext,feature_utils,ffmpeg,g2p_en,h5py,hydra,hypothesis,indicnlp,inflect,iopath,joblib,kaldi_io,kenlm,libfb,librosa,lightconv_cuda,matplotlib,misc,mmpt,mmpt_cli,model,nltk,npy_append_array,numpy,omegaconf,pandas,pathbuilder,preprocessing,progressbar,pythainlp,random_sequence_shuffler,regex,sacrebleu,sacremoses,scipy,sentencepiece,setuptools,six,sklearn,soundfile,sweep,sweep_wmt_en2de_transformer_big_common,tabulate,torch,torchaudio,tqdm,unidecode,utils,videoreader,wav2vec_cluster_faiss,wget,yaml"
skip_gitignore = true
